name: VillagerBlock
main: me.NetFire.TesCZ.VillagerBlock.main
author: TesCZ
version: 1.5
softdepend: [Residence, WorldGuard, WorldEdit]
commands:
   vreload:
      description: Reload config of this plugin
permissions:
   villagerblock.cankill:
     description: can kill villager
   villagerblock.reload:
     description: reload config
   villagerblock.trade:
     description: players can trade with villagers